@BendingMachine.Api_HostAddress = http://localhost:5095

GET {{BendingMachine.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

### Paso Test - Sadece büküm işlemi
POST {{host}}/api/Bending/test-paso
Content-Type: application/json

{
  "sideBallTravelDistance": 40.85,
  "profileLength": 670,
  "stepSize": 20,
  "evacuationTimeSeconds": 10
}
